# Log Transporter Configuration

# Source servers to collect logs from
sources:
  - name: "lb-test"
    host: "192.168.6.203"
    username: "ubuntu"
    port: 22
    ssh_key: "/app/keys/octavia_ssh_key"
    log_paths:
#      - "/var/log/nginx/access.log"
#      - "/var/log/nginx/error.log"
      - "/var/log/haproxy.log"

#  - name: "app-server-1"
#    host: "192.168.1.20"
#    username: "loguser"
#    port: 22
#    ssh_key: "/app/keys/source2_key"
#    log_paths:
#      - "/var/log/myapp/app.log"
#      - "/var/log/myapp/error.log"

#  - name: "db-server-1"
#    host: "192.168.1.30"
#    username: "loguser"
#    port: 22
#    ssh_key: "/app/keys/source3_key"
#    log_paths:
#      - "/var/log/postgresql/postgresql.log"

# Destination server configuration
destination:
  host: "10.10.10.126"
  username: "debian"
  port: 22
  ssh_key: "/app/keys/id_rsa"
  base_path: "/home/debian/logs"

# Transfer interval in seconds (for continuous mode)
interval: 30
